[package]
name = "rwfw-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rwfw-app"
path = "src/main.rs"

[dependencies]
rwfw-core = { path = "../rwfw-core" }
rwfw-shared = { path = "../rwfw-shared" }
mod-home = { path = "../modules/home" }
mod-auth = { path = "../modules/auth" }
mod-blog = { path = "../modules/blog" }
mod-demo = { path = "../modules/demo" }
tokio = { workspace = true }
tracing = { workspace = true }
inventory = { workspace = true }
axum = { workspace = true }
anyhow = { workspace = true }
rust-embed = { version = "8", features = ["interpolate-folder-path", "debug-embed"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json", "cookies"] }
serde_json = { workspace = true }
sea-orm = { workspace = true }
uuid = { workspace = true }
chromiumoxide = { version = "0.7", default-features = false, features = ["tokio-runtime"] }
futures = "0.3"
