[package]
name = "rwfw-core"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tower-sessions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }
async-trait = { workspace = true }
inventory = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
config = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
argon2 = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
mime_guess = "2"
minijinja = { version = "2", features = ["loader", "json", "loop_controls"] }
minijinja-autoreload = "2"
notify = "8"
tokio-stream = { version = "0.1", features = ["sync"] }
validator = { version = "0.20", features = ["derive"] }
rwfw-shared = { path = "../rwfw-shared" }
hyper = "1"
http = "1"
reqwest = { version = "0.12", features = ["json"] }

[dev-dependencies]
serde_urlencoded = "0.7"
