//! Stateless reactive components.
//!
//! Phase 1 exposes signed component tokens and the server-side contracts used
//! by the registry, endpoint, MiniJinja helpers, and generated dispatch code.

use serde::Serialize;
use serde::de::DeserializeOwned;

use crate::app::AppState;
use crate::auth::CurrentUser;

#[doc(hidden)]
pub use minijinja;
#[doc(hidden)]
pub use serde_json;

pub mod endpoint;
pub mod registry;
mod render;
pub mod token;

pub use registry::{RegisteredOutput, ReactiveRegistration, find, has_registered_components};
pub(crate) use render::{render_component, render_registered_output};

/// Request context passed to reactive actions.
pub struct Ctx<'a> {
    pub state: &'a AppState,
    pub user: Option<&'a CurrentUser>,
}

/// Action reply understood by the phase-1 endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reply {
    Replace { morph: bool },
    Nothing,
}

impl Default for Reply {
    fn default() -> Self {
        Self::Replace { morph: false }
    }
}

impl From<()> for Reply {
    fn from(_: ()) -> Self {
        Self::default()
    }
}

/// Normalizes action return values accepted by `#[reactive_actions]`.
pub trait IntoReactiveReply {
    fn into_reactive_reply(self) -> Result<Reply, ReactiveError>;
}

impl IntoReactiveReply for () {
    fn into_reactive_reply(self) -> Result<Reply, ReactiveError> {
        Ok(Reply::default())
    }
}

impl IntoReactiveReply for Reply {
    fn into_reactive_reply(self) -> Result<Reply, ReactiveError> {
        Ok(self)
    }
}

impl IntoReactiveReply for Result<Reply, ReactiveError> {
    fn into_reactive_reply(self) -> Result<Reply, ReactiveError> {
        self
    }
}

/// Reactive dispatch failures mapped to HTTP status codes by the endpoint.
#[derive(Debug, thiserror::Error)]
pub enum ReactiveError {
    #[error("unauthorized")]
    Unauthorized,
    #[error("not found")]
    NotFound,
    #[error("{0}")]
    Invalid(String),
    #[error("unknown action")]
    UnknownAction { action: String, allowed: &'static [&'static str] },
    #[error("internal reactive component error")]
    Internal,
}

/// Public trait implemented by `#[reactive_actions]` for each component.
pub trait ReactiveComponent: Serialize + DeserializeOwned + Send + 'static {
    const NAME: &'static str;

    fn template(&self) -> &'static str;

    fn dom_id(&self) -> String {
        Self::NAME.to_string()
    }

    fn context(&self) -> minijinja::Value;

    fn dispatch(
        &mut self,
        action: &str,
        params: serde_json::Value,
        ctx: &Ctx<'_>,
    ) -> Result<Reply, ReactiveError>;
}

/// Metadata generated by `#[derive(ReactiveComponent)]` and consumed by
/// `#[reactive_actions]`.
#[doc(hidden)]
pub trait ReactiveComponentMeta: Serialize {
    const NAME: &'static str;
    const TEMPLATE: &'static str;

    fn dom_id(&self) -> String {
        Self::NAME.to_string()
    }

    fn context(&self) -> minijinja::Value {
        minijinja::Value::from_serialize(self)
    }
}
