const { expect, test } = require(process.env.RWFW_PLAYWRIGHT_TEST_MODULE || '@playwright/test')

const baseURL = process.env.RWFW_SMOKE_BASE_URL || 'http://localhost:3000'
const adminEmail = process.env.RWFW_SMOKE_ADMIN_EMAIL || 'admin@example.com'
const adminPassword = process.env.RWFW_SMOKE_ADMIN_PASSWORD || 'rwfw-admin-123'

test('generated app renders home and product scaffold', async ({ page }) => {
  const consoleErrors = []
  page.on('console', (message) => {
    if (message.type() === 'error') {
      consoleErrors.push(message.text())
    }
  })

  await page.goto(`${baseURL}/`)
  await expect(page.getByRole('heading', { name: 'Welcome to RWFW' })).toBeVisible()

  await page.goto(`${baseURL}/auth/login`)
  await page.getByLabel('Email').fill(adminEmail)
  await page.getByLabel('Password').fill(adminPassword)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByText(adminEmail)).toBeVisible()

  await page.goto(`${baseURL}/blog/products`)
  await expect(page.getByRole('heading', { name: 'Product' })).toBeVisible()
  await page.getByRole('link', { name: 'New Product' }).click()

  await page.getByLabel('Name').fill('Smoke Product')
  await page.getByLabel('Description').fill('Generated by RWFW smoke test')
  await page.getByLabel('Active').check()
  await page.getByLabel('Price').fill('19.95')
  await page.getByLabel('Available On').fill('2026-05-11')
  await page.getByLabel('Published At').fill('2026-05-11T10:30')
  await page.getByRole('button', { name: 'Create Product' }).click()

  await expect(page).toHaveURL(`${baseURL}/blog/products`)
  await expect(page.getByText('Product created.')).toBeVisible()
  await expect(page.getByText('Smoke Product')).toBeVisible()
  await page.getByPlaceholder('Search products...').fill('Smoke')
  await page.getByRole('button', { name: 'Search' }).click()
  await expect(page).toHaveURL(/q=Smoke/)
  await expect(page.getByText('Smoke Product')).toBeVisible()

  await page.getByRole('link', { name: 'View' }).first().click()
  await expect(page.getByRole('heading', { name: /Product #/ })).toBeVisible()
  await expect(page.getByText('19.95')).toBeVisible()

  expect(consoleErrors).toEqual([])
})
